image:
  file: .gitpod.Dockerfile

tasks:
  
  # ------------------------------------
  # Setup pulsar for Astra
  # ------------------------------------
  - name: Astra Streaming
    init: |
      gp open ./Lab1/02-start-gitpod.md
      curl -O https://archive.apache.org/dist/pulsar/pulsar-2.9.2/apache-pulsar-2.9.2-bin.tar.gz
      tar xfz ./apache-pulsar-2.9.2-bin.tar.gz
    command: |
      until [ -f ./apache-pulsar-2.9.2/bin/pulsar-admin ]; do sleep 1; done=
      cd ./apache-pulsar-2.9.2

  # --------------------------------------
  #  SETUP CQLSH and Create DB Workshop
  # --------------------------------------
  - name: Astra DB
    env:
        CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    before: |
      chmod 700 ./install-cqlsh
      chmod 700 ./cqlsh
    command: |
      ./install-cqlsh
      ./cqlsh

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - GabrielBB.vscode-lombok
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
    - matt-rudge.auto-open-preview-panel