image:
  file: .gitpod.Dockerfile

tasks:

  # ------------------------------------
  # Setup pulsar for Astra
  # ------------------------------------
  - name: Astra Streaming
    init: |
      curl -O https://archive.apache.org/dist/pulsar/pulsar-2.9.2/apache-pulsar-2.9.2-bin.tar.gz
      tar xfz ./apache-pulsar-2.9.2-bin.tar.gz
    command: |
      cd /workspace/advanced-cdc-for-astra/apache-pulsar-2.9.2

  # --------------------------------------
  #  SETUP CQLSH and Create DB Workshop
  # --------------------------------------
  - name: Astra DB
    env:
        CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    before: |
      chmod 700 /workspace/advanced-cdc-for-astra/install-cqlsh.sh
      chmod 700 /workspace/advanced-cdc-for-astra/cqlsh.sh
    command: |
      /workspace/advanced-cdc-for-astra/install-cqlsh.sh
      /workspace/advanced-cdc-for-astra/cqlsh.sh
      
  # --------------------------------------
  #  SETUP ELK stack for sink store and observability
  # --------------------------------------
  - name: Elasticsearch
    command: |
      docker run --name elasticsearch -e discovery.type=single-node -p 9200:9200 -p 9300:9300 -t docker.elastic.co/elasticsearch/elasticsearch:8.2.0
  - name: Kibana
    command: |
      docker run --name kibana -p 5601:5601 docker.elastic.co/kibana/kibana:8.2.0

ports:
  - port: 9300
    onOpen: ignore
    visibility: public
  - port: 9200
    onOpen: ignore
    visibility: public
  - port: 5601
    onOpen: open-browser
    visibility: public

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - GabrielBB.vscode-lombok
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
    - matt-rudge.auto-open-preview-panel