image:
  file: .gitpod.Dockerfile

tasks:
  # - name: ELK Stack
  #   init: |
  #     docker-compose pull
  #   command: |
  #     docker-compose up

  # ------------------------------------
  # Setup pulsar for Astra
  # ------------------------------------
  - name: Astra Streaming
    init: |
      curl -O https://archive.apache.org/dist/pulsar/pulsar-2.9.2/apache-pulsar-2.9.2-bin.tar.gz
      tar xfz ./apache-pulsar-2.9.2-bin.tar.gz
    command: |
      cd /workspace/advanced-cdc-for-astra/apache-pulsar-2.9.2

  # --------------------------------------
  #  SETUP CQLSH and Create DB Workshop
  # --------------------------------------
  - name: Astra DB
    env:
        CQLENG_ALLOW_SCHEMA_MANAGEMENT: 1
    before: |
      chmod 700 /workspace/advanced-cdc-for-astra/install-cqlsh.sh
      chmod 700 /workspace/advanced-cdc-for-astra/cqlsh.sh
    command: |
      /workspace/advanced-cdc-for-astra/install-cqlsh.sh
      /workspace/advanced-cdc-for-astra/cqlsh.sh

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: true
    addLabel: false

vscode:
  extensions:
    - GabrielBB.vscode-lombok
    - vscjava.vscode-java-pack
    - Pivotal.vscode-boot-dev-pack
    - matt-rudge.auto-open-preview-panel